import pandas as pd

ndo = pd.read_csv('./nd.tsv', sep='\t')
ndm = pd.read_csv('./nd_m.tsv', sep='\t')
#my1 = pd.read_csv('./geofinal/final/geo2mesh9fall2_errorchecked.tsv', sep='\t')
#myl1 = my1['GSE'].values.tolist()
#my2 = pd.read_csv('./geofinal/final/geo2mesh9fall3_errorchecked.tsv', sep='\t')
#myl2 = my2['GSE'].values.tolist()
#my3 = pd.read_csv('./geofinal/final/geo2mesh9fall5_errorchecked.tsv', sep='\t')
#myl3 = my3['GSE'].values.tolist()
#my4 = pd.read_csv('./geofinal/final/geo2mesh562_errorchecked2.tsv', sep='\t')
#myl4 = my4['GSE'].values.tolist()
#my5 = pd.read_csv('./geofinal/final/geo2mesh3200checked2_ff.tsv', sep='\t')
#myl5 = my5['GSE'].values.tolist()
#my6 = pd.read_csv('./geofinal/final/geo2mesh7582_errorchecked.tsv', sep='\t')
#myl6 = my6['GSE'].values.tolist()
#my7 = pd.read_csv('./geofinal/final/geo2mesh_rest.tsv', sep='\t')
#myl7 = my7['GSE'].values.tolist()
#
my8 = pd.read_csv('./geofinal/final/your.tsv', sep='\t')
myl8 = my8['GSE'].values.tolist()
my9 = pd.read_csv('./geofinal/final/me.tsv', sep='\t')
myl9 = my9['GSE'].values.tolist()


tk = set(ndo['GSE'][:32000]) | set(ndo['GSE'][50000:62000]) | set(ndo['GSE'][75000:82000]) | set(ndo['GSE'][93000:])
tb = set(my8['GSE'].values) -tk
tp = set(ndo['GSE']) - set(my8['GSE'].values) - set(my9['GSE'].values) 
tt = set(my8['GSE'].values) & set(my9['GSE'].values)
print(tt)
#print(set(my9['GSE'].values))
#print(tp)
#print(len(list(set(ndo['GSE'].values))))
#print(set(ndo['GSE']))
#print(tb)
#print(len(list(tk)))
#print(len(list(set(my8['GSE'].values))))
#t1 = set(ndo['GSE'][:32000]) - set(my5['GSE'].values)
#t2 = set(ndo['GSE'][93000:]) - set(my1['GSE'].values) - set(my2['GSE'].values) - set(my3['GSE'].values)
#t3 = set(ndo['GSE'][50000:62000]) - set(my4['GSE'].values)
#t4 = set(ndo['GSE'][75000:82000]) - set(my6['GSE'].values)
#t5 = set(my1['GSE'].values) | set(my2['GSE'].values) | set(my3['GSE'].values)
## skipped 1
#t6 = t5 - set(my4['GSE'].values)
#print(t6)
#print(t2)
#print(t3)
#print(t4)
#temp3 = set(ndm['GSE'].values) - set(my1['GSE'].values) - set(my2['GSE'].values) - set(my3['GSE'].values) - set(my4['GSE'].values) - set(my5['GSE'].values) - set(my6['GSE'].values) - set(my7['GSE'].values)
#
#temp4 = set(my1['GSE'].values) | set(my2['GSE'].values) | set(my3['GSE'].values) | set(my4['GSE'].values) | set(my5['GSE'].values) | set(    my6['GSE'].values) | set(my7['GSE'].values)
#temp4 = pd.DataFrame(temp3)
#print(type(temp3))
#print(list(temp4))
#df = pd.DataFrame({'GSE': list(temp4)})

#print(len(myl1))
#print(len(myl2))
#print(len(myl3))
#print(len(myl4))
#print(len(myl5))
#print(len(myl6))
#print(len(myl7))
#ndml = ndm['GSE'].values.tolist()
#print(len(ndml))
#ndol = ndo['GSE'].values.tolist()
#print(len(ndol))
#df.to_csv("all.tsv",sep='\t', index=False)
#
